---

- name: KAFKA | Configuring service
  systemd:
    name: kafka
    state: "{{ kafka_service_state }}"
    enabled: "{{ kafka_service_enabled }}"
    daemon_reload: true

- name: KAFKA | Restart if necessary
  meta: flush_handlers

- name: KAFKA | Wait for service listening
  wait_for:
    host: "{{ kafka_host_name }}"
    port: "{{ kafka_port }}"
    state: "{{ kafka_service_state }}"
    delay: 5
    timeout: 300
  when:
    - kafka_service_enabled
    - kafka_service_state == "started"
    - kafka_service_checking

- name: KAFKA | Wait for 10 seconds
  pause: 
    seconds: 10
  when:
    - kafka_service_checking == false
